version: "3.9"

services:
  api:
    build: .
    container_name: api_casadejairo
    ports:
      - "8088:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/brend482_CasaDeJairoDB?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - EMAIL_USERNAME=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASS}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    container_name: db_casadejairo
    restart: always
    environment:
      - MYSQL_DATABASE=brend482_CasaDeJairoDB
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  db_data: